### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Ihsan48** [Henry12960/Ping38#1]
Add Constructor in PingTagTask.php

Example: 
public function __construct(Ping38 $plugin) {
    $this->plugin = $plugin;
}

And In PingTagTask.php Dont forget to Call Your Main Lime this
use Henrydm\Ping38\Ping38;

Fix in PingTagTask.php Line 10
From foreach(PingTag::getInstance()->getServer()->getOnlinePlayers() as $player){
To foreach($this->plugin->getServer()->getOnlinePlayers() as $player){

And Fix To in PingTagTask.php Line 11 
From $tag=PingTag::getInstance()->getConfig()->get("Format");
To $tag= $this->plugin->getConfig()->get("Format");

**Comment by Ihsan48** [comment]
Dont forget to add consturctor

**Comment by Henry12960** [comment]
Project discontinued!

**Comment by Henry12960** [comment]
Project discontinued!
